/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["system-health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram Login */
        post: operations["auth-telegram_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["auth-google_login"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["auth-google_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev Login */
        post: operations["auth-dev_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pets */
        get: operations["pets-list_pets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets/{pet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pet */
        get: operations["pets-get_pet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Curators */
        get: operations["curators-list_curators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shelters/{shelter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shelter */
        get: operations["shelters-get_shelter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pets/{pet_id}/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply */
        post: operations["applications-apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Applications */
        get: operations["applications-list_my_applications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/incoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incoming Applications */
        get: operations["applications-list_incoming_applications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["applications-get_application"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Application Status */
        patch: operations["applications-change_application_status"];
        trace?: never;
    };
    "/api/v1/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Upload */
        post: operations["media-create_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/uploads/{upload_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Upload */
        post: operations["media-confirm_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload */
        get: operations["media-get_upload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgeBucket
         * @enum {string}
         */
        AgeBucket: "lt1" | "1to5" | "gt5";
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            city: components["schemas"]["City"];
            housing: components["schemas"]["Housing"];
            /**
             * Household
             * @default []
             */
            household: components["schemas"]["Household"][];
            /** About */
            about?: string | null;
            /** Consent */
            consent: boolean;
        };
        /** ApplicationOut */
        ApplicationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ApplicationStatus"];
            pet: components["schemas"]["PetCardOut"];
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            city: components["schemas"]["City"];
            housing: components["schemas"]["Housing"];
            /** Household */
            household: components["schemas"]["Household"][];
            /** About */
            about: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Viewer Role
             * @enum {string}
             */
            viewer_role: "applicant" | "curator";
            /** Allowed Transitions */
            allowed_transitions: components["schemas"]["ApplicationStatus"][];
        };
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "sent" | "meeting" | "approved" | "completed" | "rejected" | "withdrawn";
        /** ApplicationStatusIn */
        ApplicationStatusIn: {
            status: components["schemas"]["ApplicationStatus"];
        };
        /**
         * ChipStatus
         * @enum {string}
         */
        ChipStatus: "none" | "planned" | "done";
        /**
         * City
         * @description Города, где работает платформа. Названия переводит фронт по ключу.
         * @enum {string}
         */
        City: "pavlodar" | "astana" | "almaty";
        /**
         * CuratorCardOut
         * @description Карточка участника: «Тёплый угол · 23 ищут дом · 41 пристроено».
         */
        CuratorCardOut: {
            /**
             * Type
             * @enum {string}
             */
            type: "shelter" | "volunteer";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            city: components["schemas"]["City"] | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Verified */
            verified: boolean;
            /** Seeking Count */
            seeking_count: number;
            /** Adopted Count */
            adopted_count: number;
        };
        /** CuratorOut */
        CuratorOut: {
            /**
             * Type
             * @enum {string}
             */
            type: "shelter" | "volunteer";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Verified */
            verified: boolean;
        };
        /**
         * CuratorType
         * @enum {string}
         */
        CuratorType: "shelter" | "volunteer";
        /** DevLoginIn */
        DevLoginIn: {
            /** Name */
            name: string;
            /** @default user */
            role: components["schemas"]["UserRole"];
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            } | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Db
             * @constant
             */
            db: "ok";
        };
        /**
         * Household
         * @enum {string}
         */
        Household: "kids" | "cats" | "dogs";
        /**
         * Housing
         * @enum {string}
         */
        Housing: "flat" | "house" | "rent";
        /** MeOut */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            city: components["schemas"]["City"] | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Verified */
            verified: boolean;
        };
        /** Page[ApplicationOut] */
        Page_ApplicationOut_: {
            /** Items */
            items: components["schemas"]["ApplicationOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /** Page[CuratorCardOut] */
        Page_CuratorCardOut_: {
            /** Items */
            items: components["schemas"]["CuratorCardOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /** Page[PetCardOut] */
        Page_PetCardOut_: {
            /** Items */
            items: components["schemas"]["PetCardOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number;
        };
        /**
         * PetCardOut
         * @description Карточка каталога. Возраст и подпись «Кошка · 4 года» собирает фронт.
         */
        PetCardOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["PetKind"];
            sex: components["schemas"]["PetSex"];
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            city: components["schemas"]["City"];
            status: components["schemas"]["PetStatus"];
            /** Sterilized */
            sterilized: boolean;
            /** Vaccinated */
            vaccinated: boolean;
            /** Traits */
            traits: components["schemas"]["PetTrait"][];
            /** Cover Url */
            cover_url: string | null;
            curator: components["schemas"]["CuratorOut"];
        };
        /**
         * PetDetailOut
         * @description Страница питомца: факты, история, фото и «Тоже ищут дом».
         */
        PetDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            kind: components["schemas"]["PetKind"];
            sex: components["schemas"]["PetSex"];
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            city: components["schemas"]["City"];
            status: components["schemas"]["PetStatus"];
            /** Sterilized */
            sterilized: boolean;
            /** Vaccinated */
            vaccinated: boolean;
            /** Traits */
            traits: components["schemas"]["PetTrait"][];
            /** Cover Url */
            cover_url: string | null;
            curator: components["schemas"]["CuratorOut"];
            /** Breed */
            breed: string | null;
            /** Weight Kg */
            weight_kg: number | null;
            /** Vaccinated At */
            vaccinated_at: string | null;
            chip: components["schemas"]["ChipStatus"];
            /** Litter Trained */
            litter_trained: boolean | null;
            /** Story Title */
            story_title: string | null;
            /** Story */
            story: string | null;
            /** Photos */
            photos: components["schemas"]["PetPhotoOut"][];
            /** Similar */
            similar: components["schemas"]["PetCardOut"][];
        };
        /**
         * PetKind
         * @enum {string}
         */
        PetKind: "cat" | "dog";
        /** PetPhotoOut */
        PetPhotoOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Card Url */
            card_url: string;
            /** Original Url */
            original_url: string;
        };
        /**
         * PetSex
         * @enum {string}
         */
        PetSex: "female" | "male";
        /**
         * PetSort
         * @enum {string}
         */
        PetSort: "new" | "old";
        /**
         * PetStatus
         * @description Один список статусов на бэке и фронте (entities/pet/model).
         *
         *     Руками куратор переключает только seeking ↔ needs_foster / treatment.
         *     reserved и adopted ставит сервис заявок при одобрении и завершении.
         * @enum {string}
         */
        PetStatus: "draft" | "seeking" | "needs_foster" | "treatment" | "reserved" | "adopted";
        /**
         * PetTrait
         * @description Ключи черт характера: фронт переводит их и строит из них чипы и фильтры.
         * @enum {string}
         */
        PetTrait: "affectionate" | "good_with_kids" | "calm" | "playful" | "quiet" | "loves_people" | "well_mannered" | "no_dogs" | "no_cats" | "apartment_ok" | "after_treatment";
        /**
         * ShelterProfileOut
         * @description Профиль приюта: шапка, статистика и блок «О приюте».
         */
        ShelterProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            city: components["schemas"]["City"];
            /** Address */
            address: string | null;
            /** About */
            about: string | null;
            /** Visit Hours */
            visit_hours: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Cover Url */
            cover_url: string | null;
            /** Verified */
            verified: boolean;
            /** On Platform Since */
            on_platform_since: number;
            /** Seeking Count */
            seeking_count: number;
            /** Adopted Count */
            adopted_count: number;
        };
        /**
         * TelegramLoginIn
         * @description Поля Telegram Login Widget — фронт шлёт их как есть.
         */
        TelegramLoginIn: {
            /** Id */
            id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name?: string | null;
            /** Username */
            username?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Auth Date */
            auth_date: number;
            /** Hash */
            hash: string;
        } & {
            [key: string]: unknown;
        };
        /** UploadCreate */
        UploadCreate: {
            purpose: components["schemas"]["UploadPurpose"];
            /**
             * Pet Id
             * Format: uuid
             */
            pet_id: string;
            /**
             * Content Type
             * @enum {string}
             */
            content_type: "image/jpeg" | "image/png" | "image/webp";
            /** Size */
            size: number;
        };
        /** UploadOut */
        UploadOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["UploadStatus"];
            /** Error */
            error: string | null;
            photo?: components["schemas"]["PetPhotoOut"] | null;
        };
        /**
         * UploadPurpose
         * @enum {string}
         */
        UploadPurpose: "pet_photo";
        /**
         * UploadStatus
         * @enum {string}
         */
        UploadStatus: "pending" | "processing" | "done" | "failed";
        /**
         * UploadTicketOut
         * @description Ответ на создание: куда и с какими заголовками браузеру делать PUT.
         */
        UploadTicketOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["UploadStatus"];
            /** Error */
            error: string | null;
            photo?: components["schemas"]["PetPhotoOut"] | null;
            /** Upload Url */
            upload_url: string;
            /**
             * Method
             * @default PUT
             * @constant
             */
            method: "PUT";
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "volunteer" | "moderator";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "system-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-telegram_login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-google_login": {
        parameters: {
            query?: {
                next?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-google_callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "auth-dev_login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevLoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "pets-list_pets": {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                q?: string | null;
                kind?: components["schemas"]["PetKind"] | null;
                age?: components["schemas"]["AgeBucket"] | null;
                city?: components["schemas"]["City"] | null;
                sterilized?: boolean | null;
                good_with_kids?: boolean | null;
                needs_foster?: boolean | null;
                shelter_id?: string | null;
                volunteer_id?: string | null;
                sort?: components["schemas"]["PetSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PetCardOut_"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "pets-get_pet": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PetDetailOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "curators-list_curators": {
        parameters: {
            query?: {
                q?: string | null;
                city?: components["schemas"]["City"] | null;
                type?: components["schemas"]["CuratorType"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CuratorCardOut_"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "shelters-get_shelter": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shelter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelterProfileOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "applications-apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "applications-list_my_applications": {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: components["schemas"]["ApplicationStatus"] | null;
                pet_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApplicationOut_"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "applications-list_incoming_applications": {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: components["schemas"]["ApplicationStatus"] | null;
                pet_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ApplicationOut_"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "applications-get_application": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "applications-change_application_status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationStatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "media-create_upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicketOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "media-confirm_upload": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "media-get_upload": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Client error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
