"""onboarding

Revision ID: 10201a565e94
Revises: 1d69713291a5
Create Date: 2026-10-05 20:27:21.741485

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "10201a565e94"
down_revision: str | Sequence[str] | None = "1d69713291a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("shelter", "volunteer", name="onboarding_type"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "submitted", "approved", "rejected", name="onboarding_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("city", postgresql.ENUM(name="city", create_type=False), nullable=True),
        sa.Column("contact_phone", sa.String(length=16), nullable=True),
        sa.Column("recommender", sa.String(length=200), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("visit_hours", sa.String(length=120), nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("shelter_id", sa.Uuid(), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_onboarding_requests_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shelter_id"],
            ["shelters.id"],
            name=op.f("fk_onboarding_requests_shelter_id_shelters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_onboarding_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onboarding_requests")),
    )
    op.create_index(
        "ix_onboarding_requests_created_at_id",
        "onboarding_requests",
        ["created_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_onboarding_requests_user_id"), "onboarding_requests", ["user_id"], unique=False
    )
    op.create_index(
        "uq_onboarding_requests_active_user",
        "onboarding_requests",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('draft', 'submitted')"),
    )
    op.create_table(
        "onboarding_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind", sa.Enum("registration", "territory_photo", name="document_kind"), nullable=False
        ),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["onboarding_requests.id"],
            name=op.f("fk_onboarding_documents_request_id_onboarding_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_onboarding_documents")),
    )
    op.create_index(
        op.f("ix_onboarding_documents_request_id"),
        "onboarding_documents",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_onboarding_documents_request_id"), table_name="onboarding_documents")
    op.drop_table("onboarding_documents")
    op.drop_index(
        "uq_onboarding_requests_active_user",
        table_name="onboarding_requests",
        postgresql_where=sa.text("status IN ('draft', 'submitted')"),
    )
    op.drop_index(op.f("ix_onboarding_requests_user_id"), table_name="onboarding_requests")
    op.drop_index("ix_onboarding_requests_created_at_id", table_name="onboarding_requests")
    op.drop_table("onboarding_requests")
    for name in ("document_kind", "onboarding_status", "onboarding_type"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
