"""feed

Revision ID: deb6be2abaa1
Revises: cd0bdeab6866
Create Date: 2026-10-05 01:46:52.605615

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "deb6be2abaa1"
down_revision: str | Sequence[str] | None = "cd0bdeab6866"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Новое значение enum autogenerate не видит — добавляем вручную.
    op.execute("ALTER TYPE upload_purpose ADD VALUE IF NOT EXISTS 'post_photo'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column(
            "author_type",
            sa.Enum("shelter", "volunteer", "owner", name="post_author_type"),
            nullable=False,
        ),
        sa.Column("shelter_id", sa.Uuid(), nullable=True),
        sa.Column("pet_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Enum("story", "help", "update", name="post_kind"), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_posts_author_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"], ["pets.id"], name=op.f("fk_posts_pet_id_pets"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["shelter_id"],
            ["shelters.id"],
            name=op.f("fk_posts_shelter_id_shelters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.create_index("ix_posts_created_at_id", "posts", ["created_at", "id"], unique=False)
    op.create_index(op.f("ix_posts_pet_id"), "posts", ["pet_id"], unique=False)
    op.create_index(op.f("ix_posts_shelter_id"), "posts", ["shelter_id"], unique=False)
    op.create_table(
        "comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("shelter_id", sa.Uuid(), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_comments_post_id_posts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["shelter_id"],
            ["shelters.id"],
            name=op.f("fk_comments_shelter_id_shelters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False)
    op.create_index(op.f("ix_comments_parent_id"), "comments", ["parent_id"], unique=False)
    op.create_index(
        "ix_comments_post_created", "comments", ["post_id", "created_at", "id"], unique=False
    )
    op.create_table(
        "post_likes",
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_likes_post_id_posts"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_post_likes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", "user_id", name=op.f("pk_post_likes")),
    )
    op.create_index(op.f("ix_post_likes_user_id"), "post_likes", ["user_id"], unique=False)
    op.create_table(
        "post_photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("card_url", sa.String(length=500), nullable=True),
        sa.Column("original_url", sa.String(length=500), nullable=True),
        sa.Column("label", sa.Enum("before", "after", name="photo_label"), nullable=True),
        sa.Column("caption", sa.String(length=80), nullable=True),
        sa.Column("position", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_photos_post_id_posts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_photos")),
    )
    op.create_index(op.f("ix_post_photos_post_id"), "post_photos", ["post_id"], unique=False)
    op.create_table(
        "comment_likes",
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_comment_likes_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_comment_likes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("comment_id", "user_id", name=op.f("pk_comment_likes")),
    )
    op.create_index(op.f("ix_comment_likes_user_id"), "comment_likes", ["user_id"], unique=False)
    op.add_column("media_uploads", sa.Column("post_id", sa.Uuid(), nullable=True))
    op.add_column(
        "media_uploads",
        sa.Column("label", postgresql.ENUM(name="photo_label", create_type=False), nullable=True),
    )
    op.add_column("media_uploads", sa.Column("caption", sa.String(length=80), nullable=True))
    op.create_index(op.f("ix_media_uploads_post_id"), "media_uploads", ["post_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_media_uploads_post_id_posts"),
        "media_uploads",
        "posts",
        ["post_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_media_uploads_post_id_posts"), "media_uploads", type_="foreignkey")
    op.drop_index(op.f("ix_media_uploads_post_id"), table_name="media_uploads")
    op.drop_column("media_uploads", "caption")
    op.drop_column("media_uploads", "label")
    op.drop_column("media_uploads", "post_id")
    op.drop_index(op.f("ix_comment_likes_user_id"), table_name="comment_likes")
    op.drop_table("comment_likes")
    op.drop_index(op.f("ix_post_photos_post_id"), table_name="post_photos")
    op.drop_table("post_photos")
    op.drop_index(op.f("ix_post_likes_user_id"), table_name="post_likes")
    op.drop_table("post_likes")
    op.drop_index("ix_comments_post_created", table_name="comments")
    op.drop_index(op.f("ix_comments_parent_id"), table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_posts_shelter_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_pet_id"), table_name="posts")
    op.drop_index("ix_posts_created_at_id", table_name="posts")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_table("posts")
    for name in ("photo_label", "post_kind", "post_author_type"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # Значение 'post_photo' в upload_purpose остаётся: PostgreSQL не умеет удалять
    # значения enum, а без колонки post_id такие загрузки уже не создать.
    # ### end Alembic commands ###
