"""favorites and subscriptions

Revision ID: 1d69713291a5
Revises: deb6be2abaa1
Create Date: 2026-10-05 01:53:23.469004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d69713291a5"
down_revision: str | Sequence[str] | None = "deb6be2abaa1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelter_subscriptions",
        sa.Column("shelter_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shelter_id"],
            ["shelters.id"],
            name=op.f("fk_shelter_subscriptions_shelter_id_shelters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_shelter_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("shelter_id", "user_id", name=op.f("pk_shelter_subscriptions")),
    )
    op.create_index(
        op.f("ix_shelter_subscriptions_user_id"), "shelter_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "pet_favorites",
        sa.Column("pet_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"], ["pets.id"], name=op.f("fk_pet_favorites_pet_id_pets"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_pet_favorites_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pet_id", "user_id", name=op.f("pk_pet_favorites")),
    )
    op.create_index(op.f("ix_pet_favorites_user_id"), "pet_favorites", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pet_favorites_user_id"), table_name="pet_favorites")
    op.drop_table("pet_favorites")
    op.drop_index(op.f("ix_shelter_subscriptions_user_id"), table_name="shelter_subscriptions")
    op.drop_table("shelter_subscriptions")
    # ### end Alembic commands ###
