"""chat

Revision ID: cd0bdeab6866
Revises: 5a64d031e1e7
Create Date: 2026-10-05 01:34:05.805114

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd0bdeab6866"
down_revision: str | Sequence[str] | None = "5a64d031e1e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("pet_id", sa.Uuid(), nullable=True),
        sa.Column("shelter_id", sa.Uuid(), nullable=True),
        sa.Column("volunteer_id", sa.Uuid(), nullable=True),
        sa.Column("user_last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("curator_last_read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(shelter_id IS NULL) <> (volunteer_id IS NULL)",
            name=op.f("ck_conversations_one_curator"),
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"], ["pets.id"], name=op.f("fk_conversations_pet_id_pets"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["shelter_id"],
            ["shelters.id"],
            name=op.f("fk_conversations_shelter_id_shelters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["volunteer_id"],
            ["users.id"],
            name=op.f("fk_conversations_volunteer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_last_message_at_id",
        "conversations",
        ["last_message_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_shelter_id"), "conversations", ["shelter_id"], unique=False
    )
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_conversations_volunteer_id"), "conversations", ["volunteer_id"], unique=False
    )
    op.create_index(
        "uq_conversations_user_pet",
        "conversations",
        ["user_id", "pet_id"],
        unique=True,
        postgresql_where=sa.text("pet_id IS NOT NULL"),
    )
    op.create_index(
        "uq_conversations_user_shelter",
        "conversations",
        ["user_id", "shelter_id"],
        unique=True,
        postgresql_where=sa.text("pet_id IS NULL AND shelter_id IS NOT NULL"),
    )
    op.create_index(
        "uq_conversations_user_volunteer",
        "conversations",
        ["user_id", "volunteer_id"],
        unique=True,
        postgresql_where=sa.text("pet_id IS NULL AND volunteer_id IS NOT NULL"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=True),
        sa.Column("side", sa.Enum("user", "curator", name="chat_side"), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("text", "system", name="message_kind"),
            server_default="text",
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
            name=op.f("fk_messages_sender_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "uq_conversations_user_volunteer",
        table_name="conversations",
        postgresql_where=sa.text("pet_id IS NULL AND volunteer_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_conversations_user_shelter",
        table_name="conversations",
        postgresql_where=sa.text("pet_id IS NULL AND shelter_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_conversations_user_pet",
        table_name="conversations",
        postgresql_where=sa.text("pet_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_conversations_volunteer_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_shelter_id"), table_name="conversations")
    op.drop_index("ix_conversations_last_message_at_id", table_name="conversations")
    op.drop_table("conversations")
    sa.Enum(name="message_kind").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="chat_side").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
