"""media uploads

Revision ID: 5a64d031e1e7
Revises: 8e3d5b21c6fa
Create Date: 2026-10-05 00:39:00.063240

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a64d031e1e7"
down_revision: str | Sequence[str] | None = "8e3d5b21c6fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.Enum("pet_photo", name="upload_purpose"), nullable=False),
        sa.Column("pet_id", sa.Uuid(), nullable=True),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "done", "failed", name="upload_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("error", sa.String(length=64), nullable=True),
        sa.Column("result_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_media_uploads_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pet_id"], ["pets.id"], name=op.f("fk_media_uploads_pet_id_pets"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_uploads")),
    )
    op.create_index(op.f("ix_media_uploads_owner_id"), "media_uploads", ["owner_id"], unique=False)
    op.create_index(op.f("ix_media_uploads_pet_id"), "media_uploads", ["pet_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_uploads_pet_id"), table_name="media_uploads")
    op.drop_index(op.f("ix_media_uploads_owner_id"), table_name="media_uploads")
    op.drop_table("media_uploads")
    sa.Enum(name="upload_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="upload_purpose").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
